# Generated by Django 5.0.6 on 2024-06-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addhospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=250)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('admin_name', models.CharField(max_length=200)),
            ],
        ),
    ]
