# Generated by Django 5.0.6 on 2024-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhospital',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
