# Generated by Django 5.0.6 on 2024-06-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0002_addhospital_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addhospital',
            name='is_available',
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('warranty_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('contract_type', models.CharField(max_length=100)),
                ('installed_at', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='Synergy.addhospital')),
            ],
        ),
    ]
