# Generated by Django 5.0.6 on 2024-06-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0003_remove_addhospital_is_available_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhospital',
            name='hospital_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
