# Generated by Django 5.0.6 on 2024-06-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0004_alter_addhospital_hospital_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhospital',
            name='hospital_id',
            field=models.IntegerField(),
        ),
    ]
