# Generated by Django 5.0.6 on 2024-06-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0006_rename_addhospital_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hospital_id',
        ),
    ]
