# Generated by Django 5.0.6 on 2024-06-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0007_remove_hospital_hospital_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='hospital',
        ),
    ]
