# Generated by Django 5.0.6 on 2024-06-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0008_remove_asset_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='Synergy.hospital'),
            preserve_default=False,
        ),
    ]
