# Generated by Django 5.0.6 on 2024-06-19 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0009_asset_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synergy.hospital'),
        ),
    ]
