# Generated by Django 5.0.6 on 2024-06-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0010_alter_asset_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField()),
                ('service_report', models.FileField(blank=True, null=True, upload_to='service_reports/')),
                ('date_reported', models.DateField()),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Synergy.asset')),
            ],
        ),
    ]
