# Generated by Django 5.0.6 on 2024-06-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0011_complaint_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_history',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Synergy.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint_history',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='null', max_length=20),
        ),
    ]
