# Generated by Django 5.0.6 on 2024-06-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0013_hospital_user_alter_complaint_history_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('discription', models.DateField(max_length=200)),
                ('supplier', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
