# Generated by Django 5.0.6 on 2024-06-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0014_purchaseorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='asset_name',
            new_name='assetname',
        ),
    ]
