# Generated by Django 5.0.6 on 2024-06-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0015_rename_asset_name_purchaseorder_assetname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_date',
        ),
    ]
