# Generated by Django 5.0.6 on 2024-07-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0016_remove_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='discription',
            field=models.CharField(max_length=200),
        ),
    ]
