# Generated by Django 5.0.6 on 2024-07-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Synergy', '0017_alter_purchaseorder_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='asset_Prise',
        ),
    ]
